package com.mycompany.asiproyecto.view;

import com.mycompany.asiproyecto.model.AlumnoContrato;
import com.mycompany.asiproyecto.service.PdfRendererService;
import java.awt.image.BufferedImage;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

public class RenderContratoJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(RenderContratoJDialog.class.getName());

    public RenderContratoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public RenderContratoJDialog(String idDocumento, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        displayPdf(idDocumento);
    }

    public void displayPdf(String driveFileId) {
        try {
            List<BufferedImage> pages = PdfRendererService.renderPdfPages(driveFileId);
            JPanel pdfContentPanel = new JPanel();
            pdfContentPanel.setLayout(new BoxLayout(pdfContentPanel, BoxLayout.Y_AXIS));

            for (BufferedImage pageImage : pages) {
                JLabel pageLabel = new JLabel(new ImageIcon(pageImage));
                pageLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
                pdfContentPanel.add(pageLabel);
                pdfContentPanel.add(Box.createVerticalStrut(10)); // Add spacing
            }

            JScrollPane scrollPane = new JScrollPane(pdfContentPanel);
            scrollPane.getVerticalScrollBar().setUnitIncrement(20);
            this.setContentPane(scrollPane);
            this.setSize(900, 700);
            this.setLocationRelativeTo(null);
            this.revalidate();
            this.repaint();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Could not load and render PDF: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RenderContratoJDialog dialog = new RenderContratoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
